# Generated by Django 2.2.4 on 2019-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190808_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='red_num',
            field=models.IntegerField(default=0),
        ),
    ]
