# Generated by Django 2.2.4 on 2019-08-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190808_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
